1.

In [2]:
#Create matrix based on input vector(N)
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix=np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
#Create similar function using np.vander
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix1=np.vander(x, N, increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
#Determitant
np.linalg.det(matrix)

287.9999999999977

In [6]:
np.linalg.det(matrix1)

287.9999999999977